# Generated by Django 3.2.4 on 2021-06-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='big_category',
        ),
        migrations.AddField(
            model_name='product',
            name='big_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.bigcategory', verbose_name='grandes catégories'),
        ),
    ]
