# Generated by Django 3.2.4 on 2021-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210609_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='big_category',
        ),
        migrations.AddField(
            model_name='product',
            name='big_category',
            field=models.ManyToManyField(to='store.BigCategory', verbose_name='grandes catégories'),
        ),
    ]
